### PR TITLE
Map ScreenHandlerListener

### PR DESCRIPTION
**Pull request by matthewperiut**
https://maven.fabricmc.net/docs/yarn-1.21+build.6/net/minecraft/screen/ScreenHandlerListener.html

### CODE REVIEW

**Review by DanyGames2014 — APPROVED** [review]
Very well documented 🙂 Me likey

**Review by MrMasrozYTLIVE — APPROVED** [review]
I honestly think it's pretty good too (Even though I am noob at Yarn-like mappings style and other stuff related to mappings)

**Comment by matthewperiut** [comment]
i made a small adjustment, all it was is to change trackedId to syncId to better match yarn.

**Review by calmilamsy — APPROVED** [review]
Perfect PR.
A link to the doc for the class, and comments on things that need it made my life much easier.

**Pull request merged**
