### PR TITLE
Biome and Noise stuff

### PR DESCRIPTION
**Pull request by danilwhale**
Maps `NoiseSampler`, `PerlinNoiseSampler`, `OctavePerlinNoiseSampler`, `SimplexNoise`, `OctaveSimplexNoiseSampler`, `BiomeSource`, `EntitySpawnGroup`

### CODE REVIEW

**Comment by matthewperiut** [comment]
There's mapping name conflicts here, see log
```
Mapping source name conflicts detected:
  fd METHOD a (()Lxv;) -> [fd/method_1781, fd/getBiomeSource]
  ew METHOD a (()Lxv;) -> [fd/method_1781, ew/getBiomeSource]
  xp METHOD a (()Lxv;) -> [fd/method_1781, xp/getBiomeSource]
  ```
  getBiomeSource is most likely named by different classes that have some sort of inheritance conflict or something like that

**Review by calmilamsy — CHANGES_REQUESTED** [review]
Please fix the name conflicts.

**Comment by danilwhale** [comment]
i don't see any issue with my PR, i mapped `BlockView#method_1781` method name to `getBiomeSource`, none of inheritors have methods with same name except the one, which is implemented as part of implementing the interface
image

also, it builds just fine
image

**Comment by matthewperiut** [comment]
use local maven and try using your mapping in intellij on b1.7.3, that's where I got the error

**Review by calmilamsy — APPROVED** [review]
I've gone and manually verified locally, yeah, I'm not seeing this name conflict that matthew is finding.

**Pull request merged**
